### ISSUE TITLE
Some Functions are missing

### ISSUE THREAD

**Issue by hanimohammad** [zhangzw16/Spatio-Temporal-Analysis-Telecom-Italia#1]
Good Day
in your project 
some functions are missing could you please provide me the last version

Milan.get_default_split_date
this function is missing

With Respect
Hani

**Comment by zhangzw16** [comment]
Thank you for reaching out.

I’m sorry to inform you that this repository has been archived and is no longer maintained. It is currently in a read-only state. However, you may consider referring to other repositories related to this dataset for further assistance.
